version: 1.0.{build}

image:
- test-vs2015-hyperv
configuration: Release
platform:
- x64

install:
- cmd: git submodule update --init --recursive

before_build:
- cmd: >-
   IF EXIST "%APPVEYOR_BUILD_FOLDER%\build" (RMDIR /s /q "%APPVEYOR_BUILD_FOLDER%\build")

   MKDIR "%APPVEYOR_BUILD_FOLDER%\build\%PLATFORM%"

   CD "%APPVEYOR_BUILD_FOLDER%\build\%PLATFORM%"

   cmake -A %PLATFORM% %APPVEYOR_BUILD_FOLDER%
build:
   project: $(APPVEYOR_BUILD_FOLDER)\build\$(PLATFORM)\libuv.sln
